config/routes.rb
require 'sidekiq/web'

Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username),
                                              ::Digest::SHA256.hexdigest(ENV['ADMIN_USERNAME'])) &
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password),
                                                ::Digest::SHA256.hexdigest(ENV['ADMIN_PASSWORD']))
end if Rails.env.production?

Rails.application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  mount Decidim::Core::Engine => '/'

  resource :organization, only: [], controller: "decidim/admin/organization" do
    member do
      patch :autofill_menu_links, action: :autofill_menu_links
      patch :autofill_footer_menu_links, action: :autofill_footer_menu_links
    end
  end

  get 'admin/user_proposal_statistic_report/:slug', to: 'decidim/govbr/user_proposals_statistic_settings#export_user_data', as: 'user_proposal_statistic_report'

  # These two routes are not present anywhere in the product
  # Instead, it's meant to be used by an advanced admin directly on URL
  # This is going to be removed once admin front-end is finished
  get(
    'admin/user_proposal_statistic_report_force_refresh/:slug',
    to: 'decidim/govbr/user_proposals_statistic_settings#force_refresh',
    as: 'user_proposal_statistic_report_force_refresh'
  )
  get(
    'admin/user_proposal_statistic_report_create/:slug',
    to: 'decidim/govbr/user_proposals_statistic_settings#create',
    as: 'user_proposal_statistic_report_create'
  )

  resources :reports, only: [:create], controller: 'decidim/reports/reports'

  patch '/update_status_comment/:id/', to: 'decidim/comments/comments#update_status', as: 'update_comment_status'

  resources :assemblies, param: :slug, only: [] do
    resources :media, only: :index, controller: 'decidim/assemblies/media'
  end

  resources :participatory_processes, param: :slug, only: [], path: :processes do
    resources :media, only: :index, controller: 'decidim/participatory_processes/media'
  end

  scope :admin do
    resources :assemblies, param: :slug, only: [] do
      resources :partners, except: [:show], controller: 'decidim/assemblies/admin/partners'
      resources :media_links, except: [:show], controller: 'decidim/assemblies/admin/media_links'
    end
  end

  scope :admin do
    resources :participatory_processes, param: :slug, only: [] do
      resources :partners, except: [:show], controller: 'decidim/participatory_processes/admin/partners'
      resources :media_links, except: [:show], controller: 'decidim/participatory_processes/admin/media_links'
      resources :user_proposals_statistic_settings, except: [:show], controller: 'decidim/participatory_processes/admin/user_proposals_statistic_settings' do
        member do
          get :export
          get :force_refresh
        end
      end
    end

    resources :participatory_process_groups, only: [] do
      resources :participatory_process_group_users,
                controller: 'decidim/participatory_processes/admin/participatory_process_group_users',
                except: [:show],
                as: :users
    end
  end
end

app/models/decidim/govbr/partner.rb
# frozen_string_literal: true

module Decidim
  module Govbr
    class Partner < ApplicationRecord
      self.table_name = "decidim_govbr_partners"

      include Decidim::Traceable
      include Decidim::Loggable
      include Decidim::HasUploadValidations

      TYPES = %w(supporter organizer).freeze

      belongs_to :partnerable, polymorphic: true

      default_scope { order(partner_type: :desc, weight: :asc) }

      has_one_attached :logo
      validates_avatar :logo, uploader: Decidim::Conferences::PartnerLogoUploader

      delegate :organization, to: :partnerable

      alias participatory_space partnerable

      def self.log_presenter_class_for(_log)
        Decidim::Govbr::AdminLog::PartnerPresenter
      end
    end
  end
end

app/controllers/decidim/assemblies/admin/partners_controller.rb
# frozen_string_literal: true

module Decidim
  module Assemblies
    module Admin
      # Controller that allows managing assembly supporters and organizers.
      #
      class PartnersController < Decidim::Assemblies::Admin::ApplicationController
        include Concerns::AssemblyAdmin
        include Decidim::Paginable

        def index
          enforce_permission_to :index, :partner

          @partners = paginate(collection)
        end

        def new
          enforce_permission_to :create, :partner
          @form = form(Decidim::Assemblies::Admin::PartnerForm).instance
        end

        def create
          enforce_permission_to :create, :partner
          @form = form(Decidim::Assemblies::Admin::PartnerForm).from_params(params)

          Decidim::Govbr::Admin::CreatePartner.call(@form, current_user, current_assembly) do
            on(:ok) do
              flash[:notice] = I18n.t("partners.create.success", scope: "decidim.admin")
              redirect_to assembly_partners_path(current_assembly)
            end

            on(:invalid) do
              flash[:alert] = I18n.t("partners.create.error", scope: "decidim.admin")
              render :new
            end
          end
        end

        def edit
          @partner = collection.find(params[:id])
          enforce_permission_to :update, :partner, partner: @partner
          @form = form(Decidim::Assemblies::Admin::PartnerForm).from_model(@partner)
        end

        def update
          @partner = collection.find(params[:id])
          enforce_permission_to :update, :partner, partner: @partner
          @form = form(Decidim::Assemblies::Admin::PartnerForm).from_params(params)

          Decidim::Govbr::Admin::UpdatePartner.call(@form, @partner) do
            on(:ok) do
              flash[:notice] = I18n.t("partners.update.success", scope: "decidim.admin")
              redirect_to assembly_partners_path(current_assembly)
            end

            on(:invalid) do
              flash.now[:alert] = I18n.t("partners.update.error", scope: "decidim.admin")
              render :edit
            end
          end
        end

        def destroy
          @partner = collection.find(params[:id])
          enforce_permission_to :destroy, :partner, partner: @partner

          Decidim::Govbr::Admin::DestroyPartner.call(@partner, current_user) do
            on(:ok) do
              flash[:notice] = I18n.t("partners.destroy.success", scope: "decidim.admin")
              redirect_to assembly_partners_path(current_assembly)
            end
          end
        end

        private

        def collection
          @collection ||= current_assembly.partners
        end
      end
    end
  end
end

app/controllers/decidim/participatory_processes/admin/partners_controller.rb
# frozen_string_literal: true

module Decidim
  module ParticipatoryProcesses
    module Admin
      # Controller that allows managing participatory process supporters and organizers.
      #
      class PartnersController < Decidim::ParticipatoryProcesses::Admin::ApplicationController
        include Concerns::ParticipatoryProcessAdmin
        include Decidim::Paginable

        def index
          enforce_permission_to :index, :partner

          @partners = paginate(collection)
        end

        def new
          enforce_permission_to :create, :partner
          @form = form(Decidim::ParticipatoryProcesses::Admin::PartnerForm).instance
        end

        def create
          enforce_permission_to :create, :partner
          @form = form(Decidim::ParticipatoryProcesses::Admin::PartnerForm).from_params(params)

          Decidim::Govbr::Admin::CreatePartner.call(@form, current_user, current_participatory_process) do
            on(:ok) do
              flash[:notice] = I18n.t("partners.create.success", scope: "decidim.admin")
              redirect_to participatory_process_partners_path(current_participatory_process)
            end

            on(:invalid) do
              flash[:alert] = I18n.t("partners.create.error", scope: "decidim.admin")
              render :new
            end
          end
        end

        def edit
          @partner = collection.find(params[:id])
          enforce_permission_to :update, :partner, partner: @partner
          @form = form(Decidim::ParticipatoryProcesses::Admin::PartnerForm).from_model(@partner)
        end

        def update
          @partner = collection.find(params[:id])
          enforce_permission_to :update, :partner, partner: @partner
          @form = form(Decidim::ParticipatoryProcesses::Admin::PartnerForm).from_params(params)

          Decidim::Govbr::Admin::UpdatePartner.call(@form, @partner) do
            on(:ok) do
              flash[:notice] = I18n.t("partners.update.success", scope: "decidim.admin")
              redirect_to participatory_process_partners_path(current_participatory_process)
            end

            on(:invalid) do
              flash.now[:alert] = I18n.t("partners.update.error", scope: "decidim.admin")
              render :edit
            end
          end
        end

        def destroy
          @partner = collection.find(params[:id])
          enforce_permission_to :destroy, :partner, partner: @partner

          Decidim::Govbr::Admin::DestroyPartner.call(@partner, current_user) do
            on(:ok) do
              flash[:notice] = I18n.t("partners.destroy.success", scope: "decidim.admin")
              redirect_to participatory_process_partners_path(current_participatory_process)
            end
          end
        end

        private

        def collection
          @collection ||= current_participatory_process.partners
        end
      end
    end
  end
end

app/views/decidim/participatory_processes/admin/partners/_form.html.erb
<div class="card">
  <div class="card-divider">
    <h2 class="card-title">
      <%= title %>
    </h2>
  </div>

  <div class="card-section">
    <div class="row column">
      <%= form.text_field :name, autofocus: true %>
    </div>

    <div class="row column">
     <%= form.select :partner_type, @form.types, { multiple: false, prompt: "" } %>
    </div>

    <div class="row column">
      <%= form.number_field :weight %>
    </div>

    <div class="row column">
      <%= form.url_field :link %>
    </div>

    <div class="row column">
      <%= form.upload :logo, required: true %>
    </div>
  </div>
</div>

app/views/decidim/participatory_processes/admin/partners/edit.html.erb
<% add_decidim_page_title(t("partners.edit.title", scope: "decidim.admin")) %>
<%= decidim_form_for(@form, url: participatory_process_partner_path(@partner.partnerable, @partner), html: { class: "form edit_partner" }) do |f| %>
  <%= render partial: "form", object: f, locals: { title: t("partners.edit.title", scope: "decidim.admin") } %>

  <div class="button--double form-general-submit">
  <%= f.submit t("partners.edit.update", scope: "decidim.admin") %>
  </div>
<% end %>

app/views/decidim/participatory_processes/admin/partners/index.html.erb
<% add_decidim_page_title(t(".title")) %>
<div class='card' id="partners">
  <div class="card-divider">
    <h2 class="card-title">
      <%= t(".title") %>
      <% if allowed_to? :create, :partner %>
         <%= link_to t("actions.new", scope: "decidim.admin", name: t("models.partner.name", scope: "decidim.admin")), new_participatory_process_partner_path(current_participatory_process), class: "button tiny button--title new" %>
      <% end %>
    </h2>
  </div>

  <div class="card-section">
    <div class="table-scroll">
      <table class="stack">
        <thead>
          <tr>
            <th><%= t("models.partner.fields.name", scope: "decidim.admin") %></th>
            <th><%= t("models.partner.fields.partner_type", scope: "decidim.admin") %></th>
            <th><%= t("models.partner.fields.link", scope: "decidim.admin") %></th>
            <th><%= t("models.partner.fields.logo", scope: "decidim.admin") %></th>

            <th class="actions"></th>
          </tr>
        </thead>
        <tbody>
          <% @partners.each do |partner| %>
            <tr>
              <td>
                <%= partner.name %>
              </td>
              <td>
                <%= t("#{partner.partner_type}", scope: "decidim.admin.models.partner.types") %>
              </td>
              <td>
                <% if partner.link.presence %>
                  <%= link_to partner.link, partner.link, target: "_blank" %>
                <% end %>
              </td>
              <td>
                <% if partner.attached_uploader(:logo).path %>
                  <%= image_tag(partner.attached_uploader(:logo).path(variant: :thumb)) %>
                <% end %>
              </td>
              <td class="table-list__actions">
                <% if allowed_to? :update, :partner, partner: partner %>
                  <%= icon_link_to "pencil", edit_participatory_process_partner_path(current_participatory_process, partner), t("actions.edit", scope: "decidim.admin"), class: "action-icon--edit" %>
                <% end %>

                <% if allowed_to? :destroy, :partner, partner: partner %>
                  <%= icon_link_to "circle-x", participatory_process_partner_path(current_participatory_process, partner), t("actions.destroy", scope: "decidim.admin"), class: "action-icon--remove", method: :delete, data: { confirm: t("actions.confirm_destroy", scope: "decidim.admin") } %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @partners, theme: "decidim" %>
    </div>
  </div>
</div>

app/views/decidim/participatory_processes/admin/partners/new.html.erb
<% add_decidim_page_title(t("partners.new.title", scope: "decidim.admin")) %>
<%= decidim_form_for(@form, html: { class: "form new_partner" }) do |f| %>
  <%= render partial: "form", object: f, locals: { title: t("partners.new.title", scope: "decidim.admin") } %>

  <div class="button--double form-general-submit">
    <%= f.submit t("partners.new.create", scope: "decidim.admin") %>
  </div>
<% end %>