config/routes.rb
require 'sidekiq/web'

Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username),
                                              ::Digest::SHA256.hexdigest(ENV['ADMIN_USERNAME'])) &
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password),
                                                ::Digest::SHA256.hexdigest(ENV['ADMIN_PASSWORD']))
end if Rails.env.production?

Rails.application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  mount Decidim::Core::Engine => '/'

  resource :organization, only: [], controller: "decidim/admin/organization" do
    member do
      patch :autofill_menu_links, action: :autofill_menu_links
      patch :autofill_footer_menu_links, action: :autofill_footer_menu_links
    end
  end

  get 'admin/user_proposal_statistic_report/:slug', to: 'decidim/govbr/user_proposals_statistic_settings#export_user_data', as: 'user_proposal_statistic_report'

  # These two routes are not present anywhere in the product
  # Instead, it's meant to be used by an advanced admin directly on URL
  # This is going to be removed once admin front-end is finished
  get(
    'admin/user_proposal_statistic_report_force_refresh/:slug',
    to: 'decidim/govbr/user_proposals_statistic_settings#force_refresh',
    as: 'user_proposal_statistic_report_force_refresh'
  )
  get(
    'admin/user_proposal_statistic_report_create/:slug',
    to: 'decidim/govbr/user_proposals_statistic_settings#create',
    as: 'user_proposal_statistic_report_create'
  )

  resources :reports, only: [:create], controller: 'decidim/reports/reports'

  patch '/update_status_comment/:id/', to: 'decidim/comments/comments#update_status', as: 'update_comment_status'

  resources :assemblies, param: :slug, only: [] do
    resources :media, only: :index, controller: 'decidim/assemblies/media'
  end

  resources :participatory_processes, param: :slug, only: [], path: :processes do
    resources :media, only: :index, controller: 'decidim/participatory_processes/media'
  end

  scope :admin do
    resources :assemblies, param: :slug, only: [] do
      resources :partners, except: [:show], controller: 'decidim/assemblies/admin/partners'
      resources :media_links, except: [:show], controller: 'decidim/assemblies/admin/media_links'
    end
  end

  scope :admin do
    resources :participatory_processes, param: :slug, only: [] do
      resources :partners, except: [:show], controller: 'decidim/participatory_processes/admin/partners'
      resources :media_links, except: [:show], controller: 'decidim/participatory_processes/admin/media_links'
      resources :user_proposals_statistic_settings, except: [:show], controller: 'decidim/participatory_processes/admin/user_proposals_statistic_settings' do
        member do
          get :export
          get :force_refresh
        end
      end
    end

    resources :participatory_process_groups, only: [] do
      resources :participatory_process_group_users,
                controller: 'decidim/participatory_processes/admin/participatory_process_group_users',
                except: [:show],
                as: :users
    end
  end
end

app/models/decidim/meetings/meeting.rb
# frozen_string_literal: true

module Decidim
  module Meetings
    # The data store for a Meeting in the Decidim::Meetings component. It stores a
    # title, description and any other useful information to render a custom meeting.
    class Meeting < Meetings::ApplicationRecord
      include Decidim::Resourceable
      include Decidim::HasAttachments
      include Decidim::HasAttachmentCollections
      include Decidim::HasComponent
      include Decidim::HasReference
      include Decidim::ScopableResource
      include Decidim::HasCategory
      include Decidim::Followable
      include Decidim::Comments::CommentableWithComponent
      include Decidim::Comments::HasAvailabilityAttributes
      include Decidim::Searchable
      include Decidim::Traceable
      include Decidim::Loggable
      include Decidim::Forms::HasQuestionnaire
      include Decidim::Paddable
      include Decidim::ActsAsAuthor
      include Decidim::Reportable
      include Decidim::Authorable
      include Decidim::TranslatableResource
      include Decidim::Publicable
      include Decidim::FilterableResource

      TYPE_OF_MEETING = %w(in_person online hybrid).freeze
      REGISTRATION_TYPE = %w(registration_disabled on_this_platform on_different_platform).freeze

      translatable_fields :title, :description, :location, :location_hints, :closing_report, :registration_terms

      has_many :registrations, class_name: "Decidim::Meetings::Registration", foreign_key: "decidim_meeting_id", dependent: :destroy
      has_many :invites, class_name: "Decidim::Meetings::Invite", foreign_key: "decidim_meeting_id", dependent: :destroy
      has_many :services, class_name: "Decidim::Meetings::Service", foreign_key: "decidim_meeting_id", dependent: :destroy
      has_one :agenda, class_name: "Decidim::Meetings::Agenda", foreign_key: "decidim_meeting_id", dependent: :destroy
      has_one :poll, class_name: "Decidim::Meetings::Poll", foreign_key: "decidim_meeting_id", dependent: :destroy
      has_many(
        :public_participants,
        -> { merge(Registration.public_participant) },
        through: :registrations,
        class_name: "Decidim::User",
        foreign_key: :decidim_user_id,
        source: :user
      )

      enum iframe_access_level: [:all, :signed_in, :registered], _prefix: true
      enum iframe_embed_type: [:none, :embed_in_meeting_page, :open_in_live_event_page, :open_in_new_tab], _prefix: true

      component_manifest_name "meetings"

      validates :title, presence: true

      geocoded_by :address

      scope :published, -> { where.not(published_at: nil) }
      scope :past, -> { where(arel_table[:end_time].lteq(Time.current)) }
      scope :upcoming, -> { where(arel_table[:end_time].gteq(Time.current)) }
      scope :withdrawn, -> { where(state: "withdrawn") }
      scope :except_withdrawn, -> { where.not(state: "withdrawn").or(where(state: nil)) }
      scope :with_availability, lambda { |state_key|
        case state_key
        when "withdrawn"
          withdrawn
        else
          except_withdrawn
        end
      }
      scope_search_multi :with_any_date, [:upcoming, :past]
      scope :with_any_space, lambda { |*target_space|
        target_spaces = target_space.compact.compact_blank

        return self if target_spaces.blank? || target_spaces.include?("all")

        joins(:component).where(
          decidim_components: { participatory_space_type: target_spaces.map(&:classify) }
        )
      }

      scope :visible_for, lambda { |user|
        (all.distinct if user&.admin?) ||
          if user.present?
            spaces = Decidim.participatory_space_registry.manifests.filter_map do |manifest|
              table_name = manifest.model_class_name.constantize.try(:table_name)
              next if table_name.blank?

              {
                name: table_name.singularize,
                class_name: manifest.model_class_name
              }
            end
            user_role_queries = spaces.map do |space|
              roles_table = "#{space[:name]}_user_roles"
              next unless connection.table_exists?(roles_table)

              "SELECT decidim_components.id FROM decidim_components
              WHERE CONCAT(decidim_components.participatory_space_id, '-', decidim_components.participatory_space_type)
              IN
              (SELECT CONCAT(#{roles_table}.#{space[:name]}_id, '-#{space[:class_name]}')
              FROM #{roles_table} WHERE #{roles_table}.decidim_user_id = ?)
              "
            end

            query = "
              decidim_meetings_meetings.private_meeting = ?
              OR decidim_meetings_meetings.transparent = ?
              OR decidim_meetings_meetings.id IN (
                SELECT decidim_meetings_registrations.decidim_meeting_id FROM decidim_meetings_registrations WHERE decidim_meetings_registrations.decidim_user_id = ?
              )
              OR decidim_meetings_meetings.decidim_component_id IN (
                SELECT decidim_components.id FROM decidim_components
                WHERE CONCAT(decidim_components.participatory_space_id, '-', decidim_components.participatory_space_type)
                IN
                  (SELECT CONCAT(decidim_participatory_space_private_users.privatable_to_id, '-', decidim_participatory_space_private_users.privatable_to_type)
                  FROM decidim_participatory_space_private_users WHERE decidim_participatory_space_private_users.decidim_user_id = ?)
              )
            "
            if user_role_queries.any?
              query = "#{query} OR decidim_meetings_meetings.decidim_component_id IN
                (#{user_role_queries.compact.join(" UNION ")})
              "
            end

            where(Arel.sql(query).to_s, false, true, user.id, user.id, *user_role_queries.compact.map { user.id }).published.distinct
          else
            published.visible
          end
      }

      scope :visible, -> { where("decidim_meetings_meetings.private_meeting != ? OR decidim_meetings_meetings.transparent = ?", true, true) }

      scope :authored_by, ->(author) { where(decidim_author_id: author) }

      scope_search_multi :with_any_type, TYPE_OF_MEETING.map(&:to_sym)

      TYPE_OF_MEETING.each do |type|
        scope type.to_sym, -> { where(type_of_meeting: type.to_sym) }
        scope :"not_#{type}", -> { where.not(type_of_meeting: type.to_sym) }
      end

      searchable_fields({
                          scope_id: :decidim_scope_id,
                          participatory_space: { component: :participatory_space },
                          A: :title,
                          D: [:description, :address],
                          datetime: :start_time
                        },
                        index_on_create: ->(meeting) { meeting.visible? && meeting.published? },
                        index_on_update: ->(meeting) { meeting.visible? && meeting.published? })

      # we create a salt for the meeting only on new meetings to prevent changing old IDs for existing (Ether)PADs
      before_create :set_default_salt

      def self.participants_iframe_embed_types
        iframe_embed_types.except(:open_in_live_event_page)
      end

      # Return registrations of a particular meeting made by users representing a group
      def user_group_registrations
        registrations.where.not(decidim_user_group_id: nil)
      end

      # Returns the presenter for this author, to be used in the views.
      # Required by ActsAsAuthor.
      def presenter
        Decidim::Meetings::MeetingPresenter.new(self)
      end

      def self.log_presenter_class_for(_log)
        Decidim::Meetings::AdminLog::MeetingPresenter
      end

      def can_be_joined_by?(user)
        !closed? && registrations_enabled? && can_participate?(user)
      end

      def can_register_invitation?(user)
        !closed? && registrations_enabled? &&
          can_participate_in_space?(user) && user_has_invitation_for_meeting?(user)
      end

      def closed?
        closed_at.present?
      end

      def past?
        end_time < Time.current
      end

      def emendation?
        false
      end

      def has_available_slots?
        return true if available_slots.zero?

        (available_slots - reserved_slots) > registrations.count
      end

      def remaining_slots
        available_slots - reserved_slots - registrations.count
      end

      def subscribers_count
        registrations.count
      end

      def has_registration_for?(user)
        registrations.where(user: user).any?
      end

      def maps_enabled?
        component.settings.maps_enabled?
      end

      # Public: Overrides the `accepts_new_comments?` CommentableWithComponent concern method.
      def accepts_new_comments?
        commentable? && !component.current_settings.comments_blocked && comments_allowed?
      end

      # Public: Overrides the `allow_resource_permissions?` Resourceable concern method.
      def allow_resource_permissions?
        component.settings.resources_permissions_enabled
      end

      # Public: Overrides the `comments_have_alignment?` Commentable concern method.
      def comments_have_alignment?
        true
      end

      # Public: Overrides the `comments_have_votes?` Commentable concern method.
      def comments_have_votes?
        true
      end

      # Public: Override Commentable concern method `users_to_notify_on_comment_created`
      def users_to_notify_on_comment_created
        followers
      end

      def can_participate?(user)
        can_participate_in_space?(user) && can_participate_in_meeting?(user)
      end

      def current_user_can_visit_meeting?(user)
        Decidim::Meetings::Meeting.visible_for(user).exists?(id: id)
      end

      def iframe_access_level_allowed_for_user?(user)
        case iframe_access_level
        when "all"
          true
        when "signed_in"
          user.present?
        else
          has_registration_for?(user)

app/controllers/concerns/decidim/meetings/component_filterable.rb
# frozen_string_literal: true

require "active_support/concern"

module Decidim
  module Meetings
    # A controller concern to specify default filter parameters for the
    # controller resources within a meetings component.
    module ComponentFilterable
      extend ActiveSupport::Concern

      included do
        private

        def default_filter_params
          {
            search_text_cont: "",
            with_any_date: "upcoming",
            activity: "all",
            with_availability: "",
            with_any_scope: default_filter_scope_params,
            with_any_category: default_filter_category_params,
            with_any_state: nil,
            with_any_origin: default_filter_origin_params,
            with_any_type: default_filter_type_params
          }
        end
      end
    end
  end
end

app/views/decidim/meetings/admin/meetings/index.html.erb
<% add_decidim_page_title(t(".title")) %>
<div class="card">
  <div class="card-divider">
    <h2 class="card-title">
        <%= translated_attribute(current_component.name).capitalize %>
      <div class="button--title">
        <% if translated_attribute(current_component.singular_name).present? %>
            <%= link_to t("decidim.components.meetings.actions.new", singular_name: translated_attribute(current_component.singular_name).downcase), new_meeting_path, class: "button tiny button--simple" if allowed_to? :create, :meeting %>
        <% else %>
            <%= link_to t("decidim.components.meetings.actions.new", singular_name: "reunião"), new_meeting_path, class: "button tiny button--simple" if allowed_to? :create, :meeting %>
        <% end %>
        <%= export_dropdown %>
      </div>
    </h2>
  </div>

  <%= admin_filter_selector(:meetings) %>
  <div class="card-section">
    <div class="table-scroll">
      <table class="table-list">
        <thead>
          <tr>
            <th>
              <%= sort_link(query, :id, t("models.meeting.fields.id", scope: "decidim.meetings"), default_order: :desc ) %>
            </th>
            <th>
              <%= sort_link(query, :translated_title, t("models.meeting.fields.title", scope: "decidim.meetings"), default_order: :desc ) %>
            </th>
            <th>
              <%= sort_link(query, :start_time, t("models.meeting.fields.start_time", scope: "decidim.meetings"), default_order: :desc ) %>
            </th>
            <th>
              <%= sort_link(query, :end_time, t("models.meeting.fields.end_time", scope: "decidim.meetings"), default_order: :desc ) %>
            </th>
            <th>
              <%= sort_link(query, :closed, t("models.meeting.fields.closed", scope: "decidim.meetings"), default_order: :desc ) %>
            </th>
            <% if maps_enabled? && Decidim::Map.available?(:static, :geocoding) %>
              <th><%= t("models.meeting.fields.map", scope: "decidim.meetings") %></th>
            <% end %>
            <% if resource_with_scopes_enabled? %>
              <th>
                <%= sort_link(query, :scope_name, t("models.proposal.fields.scope", scope: "decidim.proposals") ) %>
              </th>
            <% end %>
            <th class="actions"><%= t("actions.title", scope: "decidim.meetings") %></th>
          </tr>
        </thead>
        <tbody>
          <% meetings.each do |meeting| %>
            <tr data-id="<%= meeting.id %>">
              <td>
                <%= meeting.id %><br>
              </td>
              <td>
                <%= present(meeting).title(html_escape: true) %><br>
              </td>
              <td>
                <% if meeting.start_time %>
                  <%= l meeting.start_time, format: :long %>
                <% end %>
              </td>
              <td>
                <% if meeting.end_time %>
                  <%= l meeting.end_time, format: :long %>
                <% end %>
              </td>
              <td>
                <%= humanize_boolean meeting.closed? %>
              </td>
              <% if maps_enabled? && Decidim::Map.available?(:static, :geocoding) %>
                <td>
                  <%= static_map_link(meeting) %>
                </td>
              <% end %>
              <%= td_resource_scope_for(meeting.scope) %>
              <td class="table-list__actions">
                <% if allowed_to? :update, :meeting, meeting: meeting %>
                  <% if meeting.published? %>
                    <%= icon_link_to "x", unpublish_meeting_path(meeting), t("actions.unpublish", scope: "decidim.admin"), method: :put, class: "action-icon--unpublish", data: { confirm: t("actions.unpublish", scope: "decidim.admin") } %>
                  <% else %>
                    <%= icon_link_to "check", publish_meeting_path(meeting), t("actions.publish", scope: "decidim.admin"), method: :put, class: "action-icon--publish" %>
                  <% end %>
                <% else %>
                  <span class="action-space icon"></span>
                <% end %>

                <%= icon_link_to "eye", resource_locator(meeting).path, t("actions.preview", scope: "decidim.meetings"), class: "action-icon--preview", target: :blank %>

                <% if allowed_to? :copy, :meeting, meeting: meeting %>
                  <%= icon_link_to "clipboard", new_meeting_copy_path(meeting), t("actions.duplicate", scope: "decidim.admin"), class: "action-icon--copy" %>
                <% else %>
                  <span class="action-space icon"></span>
                <% end %>

                <% if allowed_to? :update, :meeting, meeting: meeting %>
                  <% if meeting.registration_disabled? %>
                    <%= icon "people", class: "action-icon action-icon--disabled", role: "img", aria_label: t("actions.registrations", scope: "decidim.meetings") %>
                  <% else %>
                    <%= icon_link_to "people", meeting.on_this_platform? ? edit_meeting_registrations_path(meeting) : meeting.registration_url, t("actions.registrations", scope: "decidim.meetings"), class: "action-icon--registrations" %>
                  <% end %>
                <% end %>

                <% if allowed_to? :update, :meeting, meeting: meeting %>
                  <%= icon_link_to "pencil", edit_meeting_path(meeting), t("actions.edit", scope: "decidim.meetings"), class: "action-icon--edit" %>
                  <%= icon_link_to "calendar", meeting.agenda.present? ? edit_meeting_agenda_path(meeting, meeting.agenda) : new_meeting_agenda_path(meeting), t("actions.agenda", scope: "decidim.meetings"), class: "action-icon--agenda" %>
                  <%= icon_link_to "list", edit_meeting_poll_path(meeting), t("actions.manage_poll", scope: "decidim.meetings"), class: "action-icon--manage-poll-questionnaire" %>
                <% else %>
                  <span class="action-space icon"></span>
                  <span class="action-space icon"></span>
                  <span class="action-space icon"></span>
                <% end %>

                <% if allowed_to? :close, :meeting, meeting: meeting %>
                  <%= icon_link_to "lock-locked", edit_meeting_meeting_close_path(meeting_id: meeting.id, id: meeting.id), t("actions.close", scope: "decidim.meetings"), class: "action-icon--close" %>
                <% else %>
                    <span class="action-space icon"></span>
                <% end %>

                <% if allowed_to? :update, :meeting, meeting: meeting %>
                    <%= icon_link_to "folder", meeting_attachment_collections_path(meeting), t("actions.attachment_collections", scope: "decidim.meetings"), class: "action-icon--attachment_collections" %>
                <% else %>
                    <span class="action-space icon"></span>
                <% end %>

                <% if allowed_to? :update, :meeting, meeting: meeting %>
                  <%= icon_link_to "paperclip", meeting_attachments_path(meeting), t("actions.attachments", scope: "decidim.meetings"), class: "action-icon--attachments" %>
                <% else %>
                  <span class="action-space icon"></span>
                <% end %>

                <%= resource_permissions_link(meeting) %>

                <% if allowed_to? :destroy, :meeting, meeting: meeting %>
                  <% if present(meeting).authored_proposals.empty? %>
                    <%= icon_link_to "circle-x", meeting_path(meeting), t("actions.destroy", scope: "decidim.meetings"), method: :delete, class: "action-icon--remove", data: { confirm: t("actions.confirm_destroy", scope: "decidim.meetings") } %>
                  <% else %>
                    <%=
                      content_tag(:button,
                                  class: ["action-icon", "action-icon--remove", "destroy-meeting-alert"],
                                  "data-invalid-destroy-message" => t("actions.invalid_destroy.proposals_count", count: present(meeting).authored_proposals.size, scope: "decidim.meetings"),
                                  "data-proposal-titles" => present(meeting).formatted_proposals_titles) do
                        content_tag(:span,
                                    data: { tooltip: true, disable_hover: false, click_open: false },
                                    title: t("actions.destroy", scope: "decidim.meetings")) do
                          icon("circle-x")
                        end
                      end
                    %>
                  <% end %>
                <% else %>
                  <span class="action-space icon"></span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate meetings, theme: "decidim" %>
    </div>
  </div>
</div>

<%= javascript_pack_tag "decidim_meetings_admin" %>